### ISSUE TITLE
Enterprise team

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/myplanet#1985] opened 2020-07-14 04:06 UTC
Enterprise team is not showing name of team members even when i am logged in as leader

**Comment by leomaxi** [comment] 2020-07-14 14:52
> Enterprise team is not showing name of team members even when i am logged in as leader

@lmmrssa ,  Please expand issue more for a clearer understanding / how do we reproduce this? [Enterprise -> Team is showing on my device] Kindly help re-produce the bug. 

<img width="1284" alt="Screenshot 2020-07-14 at 2 49 32 PM" src="https://user-images.githubusercontent.com/2836302/87440369-691c5780-c5e1-11ea-8f26-a9611922a55f.png">

**Comment by avin-sharma** [comment] 2020-07-29 16:08
Are we still facing this problem? I was unable to reproduce it.

**Comment by avin-sharma** [comment] 2020-07-29 16:49
This was fixed in #1963

**Closed by avin-sharma** 2020-07-29 16:49 UTC
