### ISSUE TITLE
Course progress size issue : less than api level 21

### ISSUE THREAD

**Issue by rrijal53** [open-learning-exchange/myplanet#620] opened 2019-03-01 16:34 UTC
Problem still exists in courses list but working in course detail.
![screenshot_1551457927](https://user-images.githubusercontent.com/9145217/53652003-f458af80-3c6f-11e9-81e5-a9cb09e1632f.png)
![screenshot_1551457942](https://user-images.githubusercontent.com/9145217/53652004-f458af80-3c6f-11e9-93e1-19b6acf262d4.png)

**Comment by jazdao** [comment] 2019-03-18 19:14
Hi @rrijal53, is that the same page?  May I ask what the API level of that emulator is?

**Comment by zelmi** [comment] 2019-04-18 19:52
This progress bar seems to have already been changed. It no longer looks like the images above.

<img width="1440" alt="Screen Shot 2019-04-18 at 3 48 46 PM" src="https://user-images.githubusercontent.com/29234807/56387199-b0a31080-61f1-11e9-97f9-ffc6ca9a753a.png">

<img width="1440" alt="Screen Shot 2019-04-18 at 3 49 08 PM" src="https://user-images.githubusercontent.com/29234807/56387204-b39e0100-61f1-11e9-8113-e60f0a25029f.png">

Or is the problem not with the progress bar? This issue does not highlight exactly what the problem is.

**Comment by rrijal53** [comment] 2019-04-19 04:01
@zelmi The problem is in myPlanet android application , not in planet web application. You have posted screenshot of planet .

**Comment by zelmi** [comment] 2019-04-24 20:51
@rrijal53 It seems this issue has already been fixed in the merged [PR #546](https://github.com/open-learning-exchange/myplanet/pull/546). This problem no longer occurs in the android application. This is the current state of the progress bar:

### A course before it is started:

<img width="455" alt="Screen Shot 2019-04-24 at 4 07 29 PM" src="https://user-images.githubusercontent.com/29234807/56692217-b1371d80-66af-11e9-91ce-c3b7ef8f6ed7.png">

### First entering the course:

<img width="455" alt="Screen Shot 2019-04-24 at 4 07 39 PM" src="https://user-images.githubusercontent.com/29234807/56692251-c9a73800-66af-11e9-941a-87c49a7079f7.png">

### The progression of the bar as `Next` button is clicked:

<img width="455" alt="Screen Shot 2019-04-24 at 4 07 46 PM" src="https://user-images.githubusercontent.com/29234807/56692318-ee031480-66af-11e9-9e59-a28aa37000b2.png">

### Last page of the course:

<img width="455" alt="Screen Shot 2019-04-24 at 4 07 52 PM" src="https://user-images.githubusercontent.com/29234807/56692334-f8251300-66af-11e9-9367-354f4652b0d8.png">

### Once the course has been completed:

<img width="455" alt="Screen Shot 2019-04-24 at 4 08 01 PM" src="https://user-images.githubusercontent.com/29234807/56692389-12f78780-66b0-11e9-870e-844eb802d656.png">

Please allow this issue to be closed if it is no longer valid.

**Comment by rrijal53** [comment] 2019-04-25 06:47
@zelmi  no, you are testing it on api version 28 , please test it on api version 21 and older. ie android lollipop.

**Comment by leomaxi** [comment] 2019-12-20 18:14
Not Requred

**Closed by leomaxi** 2019-12-20 18:14 UTC
Labels: newbie friendly, priority
