### ISSUE TITLE
Health: Self examination not syncing

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/myplanet#1792] opened 2020-06-02 02:39 UTC
Steps to reproduce:

1. Create a new member in myHealth and add an examination
  a. I did this step offline.  Not sure if it matters.
2. Sync to planet
3. Log in as the new user in myPlanet
4. Sync health record
5. Create a new examination record in myHealth
6. Sync while logged in as the new user
7. New examination will not show up in Planet

If you log in as the health worker and sync then the examination will show up in Planet.

**Comment by rrijal53** [comment] 2020-06-02 15:27
@paulbert @leomaxi  i m not able to reproduce the issue .
![Screenshot_1591111544](https://user-images.githubusercontent.com/9145217/83538567-af2bc900-a515-11ea-9566-1154d447fb8d.png)
<img width="530" alt="Screen Shot 2020-06-02 at 21 11 12" src="https://user-images.githubusercontent.com/9145217/83538582-b4891380-a515-11ea-80f1-c4f24bfca24d.png">

**Comment by leomaxi** [comment] 2020-06-02 17:05
Tried twice. Couldn't reproduce .. Cann you help @paulbert to reproduce this?

<img width="960" alt="Screenshot 2020-06-02 at 5 02 28 PM" src="https://user-images.githubusercontent.com/2836302/83548261-040a1800-a4f3-11ea-857c-8d84d175c46b.png">
<img width="739" alt="Screenshot 2020-06-02 at 5 04 22 PM" src="https://user-images.githubusercontent.com/2836302/83548321-1e43f600-a4f3-11ea-9872-bb4fd98d9118.png">

**Comment by leomaxi** [comment] 2020-06-19 15:19
Closing. Not able  to  reproduce the error

**Closed by leomaxi** 2020-06-19 15:19 UTC
